services:
  kivy_android:
    build: .
    container_name: kivy_android_builder
    volumes:
      - .:/home/builduser/app  # Mounts everything in your project root
      - buildozer_cache:/home/builduser/.buildozer
    working_dir: /home/builduser/app
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
    command: buildozer android debug
    ports:
      - 5000:5000  # Expose port 5000 for the app
    stdin_open: true
    tty: true

volumes:
  buildozer_cache: