# Dockerfile
FROM python:3.11-slim

# Install dependencies, including mtdev
RUN apt-get update && apt-get install -y \
    python3-pip \
    python3-tk \
    libgl1-mesa-glx \
    libglib2.0-0 \
    libmtdev-dev \
    mtdev-tools \
    x11-apps \
    && rm -rf /var/lib/apt/lists/*
    
WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 5001

CMD ["python", "main.py"]