version: '3.8'

services:
  shary_app:
    build: .
    container_name: shary_kivy_flask
    ports:
      - "5001:5001"
    volumes:
      - .:/app
      - shary_db_data:/app/shary_db_demo
    environment:
      FLASK_ENV: development
      FLASK_APP: app.py
    command: python main.py
    tty: true

volumes:
  shary_db_data:
    driver: local