# --- views/add_field_dialog.kv ---
#:kivy 2.3.0

<AddField>:
    MDBoxLayout:
        id: add_field_layout
        orientation: 'vertical'
        padding: '20dp'

        MDTextField:
            id: key_input
            hint_text: "Key"
            helper_text: "Enter the key"
            helper_text_mode: "on_focus"

        MDTextField:
            id: value_input
            hint_text: "Value"
            helper_text: "Enter the value"
            helper_text_mode: "on_focus"
